### PR TITLE
add highlighting of intrinsic functions (sin, cos, etc.), public, pri…

### PR DESCRIPTION
**Pull request by rmcdermo**
…vate, %, logical operations, allocatable, pointer

### CODE REVIEW

**Comment by 315234** [comment]
Thanks for the first third party pull request! Accepting this for now. In Future I think intrinsic functions should have their own scope of support.function.fortran.

**Comment by rmcdermo** [comment]
Thanks for accepting.  Admittedly, what I've added is a crude hack, as I don't know xml at all.  Just played until I got the highlighting to work.  I'll try to get the intrinsics into their own scope when I get time.  The other thing that I think would be good---but have not figured out---is to completely remove C and c in the first line as comment indicators as these are often needed as code variables.  But I'm sure this is buried in the punchcard code.  Cheers...

**Comment by 315234** [comment]
I'm not intending to do too much development on this package besides what people submit. With ST3 build 3084 there was a new syntax highlighting file format, and I have written a better fortran package for that. You can find it here if you're interested:

https://github.com/315234/SublimeFortran

The new syntax reverts back to having two separate syntaxes for f77 and f90 onwards, because of the breaking changes between the languages, like the comment problem you mention. However I'm finding that Fortran code in the wild is such a random mix of the two that it becomes messy.

**Comment by rmcdermo** [comment]
OK, thanks for the info.  I'll check that out.

**Pull request merged**
